source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target :'CognitoAuthSample' do
    pod 'AWSMobileClient', '~> 2.6.6'
    pod 'AWSCognitoAuth', '~> 2.6.7'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSCognito'
    pod 'AWSAPIGateway', '~> 2.6.2'
    pod 'Alamofire', '~> 4.5'
end
